### ISSUE TITLE
Top margin issue with ios runtime 3.4.1

### ISSUE THREAD

**Issue by davecoffin** [nstudio/nativescript-pulltorefresh#37]
Check this out:

https://cl.ly/opvQ

Youll notice when I navigate to a view that has a pulltorefresh in it, the margin that is reserved normally for the spinner is shown, then adjusts. Its not pretty. If I remove the pulltorefresh, it works as expected. Thoughts?

**Comment by davecoffin** [comment]
Here's a playground illustrating the issue: https://play.nativescript.org/?template=play-js&id=KSXAup&v=2

**Comment by davecoffin** [comment]
Some more info:
Its something to do with the new Action Bars in iOS 11. The bug exists when going from one page with an action bar to another page (the page with the pull refresh) with an action bar. Here are some demos:

Going from action bar to no action bar: https://cl.ly/oqIG
Going from no action bar to no action bar: https://cl.ly/oqJo
Going from no action bar to action bar: https://cl.ly/oqDp

**Comment by PeterStaev** [comment]
Logged https://github.com/NativeScript/NativeScript/issues/5274

**Comment by bradmartin** [comment]
I meant to ping in earlier, Hristo on the core team is redoing a bunch of the frame in NS. I know some fixes for iPhoneX are to land and a bunch of others so this could be related to the work he's doing there.

**Comment by mrpaaske** [comment]
I still have the same issue with this plugin and iPhone X. Setting `margin-top: -44` hides the bug. I'm not sure if this is NativeScript issue or plugin issue.

Also, `ActionBar` is not involved in my case.
