### ISSUE TITLE
PullRefresh:PullToRefresh around simple <Label /> crashes on Android

### ISSUE THREAD

**Issue by xingyuli** [nstudio/nativescript-pulltorefresh#38]
I have a page composed by non-list views. The `PullToRefresh` plugin works on iOS but crashes on Android. Does that mean this plugin not support this kind of page? If yes, then non-list pages would cry.

```xml
<Page class="page"
    navigatingTo="onNavigatingTo"  
    xmlns="http://schemas.nativescript.org/tns.xsd"
    xmlns:PullRefresh="nativescript-pulltorefresh">

    <PullRefresh:PullToRefresh refresh="onRefresh">
        <ScrollView>
            <!-- crashes if I comment out this line, the problem is not caused by non-scrollable as you can add tens of Label's here -->
            <!-- <Label text="Label 1" /> -->
        </ScrollView>
    </PullRefresh:PullToRefresh>
</Page>
```

Crash screenshot:
![screenshot_2018-01-23-15-19-06-913_org nativescri](https://user-images.githubusercontent.com/3337431/35262770-021dcf76-0051-11e8-9fe7-6e0d17baef9b.png)

You can reproduce the crash with other view as well, e.g., SegmentedBar (which I originally came across this issue).

**Comment by reinaldorauch** [comment]
+1

**Comment by markosole** [comment]
Guys same problem here. My code is a bit longer, so here is a picture instead and if I lines with text it just stops working. Another thing is that SearchBar does not work nether. 
Is there any solution for this?
![image](https://user-images.githubusercontent.com/10780405/62673538-aa01fa00-b996-11e9-85b5-390484e4858b.png)

**Comment by markosole** [comment]
Ok, solution is: `<label text="Here is some dummy text" color="#c3c3c3"  textWrap="true"/> `
Just add **color="#c3c3c3"** and it will work. Adjust the color by your needs. It is still a problem but it can be addressed with this tweak

**Comment by DvDave** [comment]
+1
I've added a general `Label{
color:black;
}`
and this solve the issue. 
After 2 hours of headache of course :)
