### ISSUE TITLE
Not working with webview on android, for ios works fine

### ISSUE THREAD

**Issue by bajmera** [nstudio/nativescript-pulltorefresh#59]
I have integrated this plugin with nativescript webview, i wants to refresh page inside webview
While scrolling down, page is getting refreshed, but its affecting to webview CSS for modal and some angular components

Showing black background behind modal popup

Please provide solution

**Comment by krthush** [comment]
I'm following up on this, just trying testing on Android s8+ (Android 9) with a webview on a vue project, here are few snippets of the keycode:

![image](https://user-images.githubusercontent.com/33790334/67209766-e24e9b80-f40f-11e9-9bc0-aab62003d763.png)

![image](https://user-images.githubusercontent.com/33790334/67209807-f4303e80-f40f-11e9-9a35-ccbb96af4cec.png)

The webpage loads fine at the start (this was working anyways before the addition of pulltorefresh) and the pull to refresh animation occurs itself (i.e. for android the spinner appears) but it doesn't actually refresh the page.

I have yet to test on iOS

**Comment by krthush** [comment]
Just tested on iOS, same results - the webview doesn't get affect at all, but the native spinner does appear.

**Comment by krthush** [comment]
Actually... ignore me I just realised I thought this component refreshes the component for you, but its actually a visually plugin to show the spinner for android/ios, and you need to refresh the component yourself. I have now managed this with this...

```
      refreshList(args) {
        this.$refs.dashboard._nativeView.reload();
        var pullRefresh = args.object;
        setTimeout(function() {
          pullRefresh.refreshing = false;
        }, 1000);
      }
```

Now everything works as expected 🚀  Thanks for the plugin!

**Comment by NazimMertBilgi** [comment]
I finally found a solution.

Strangely, the buttons on some websites were not working properly. It didn't look right.

With this cheat, it now works smoothly.

```
<PullToRefresh (refresh)="refreshPage($event)" indicatorFillColor="#fff000"
        indicatorColor="#3489db">
        <GridLayout>
            <WebView (loadStarted)="onLoadStarted($event)" src="{{ webViewSrc }}"></WebView>
        </GridLayout>
    </PullToRefresh>
```
