### ISSUE TITLE
Android ViewPager2 increased sensitivity 

### ISSUE THREAD

**Issue by romandragan** [nstudio/nativescript-pulltorefresh#62]
If I use `PullToRefresh` inside Android's `ViewPager2` fragment ([`nativescript-pager`](https://github.com/triniwiz/nativescript-pager)) plugin, the sensitivity of the pages increases a lot.

Seems like working on iOS.

cc @triniwiz

**Comment by romandragan** [comment]
UPD. Was able to resolve that with:

```
args.object.android.setNestedScrollingEnabled(true)
```

in the loaded events of `ListView` and `Pager` components.

**Comment by triniwiz** [comment]
@romandragan the ViewPager2 uses RecyclerView so that's why that is happening now
