### ISSUE TITLE
Cannot access 'PullToRefresh' before initialization

### ISSUE THREAD

**Issue by iamabs2001** [nstudio/nativescript-pulltorefresh#74]
ERROR TypeError: Could not load view for: PullToRefresh.ReferenceError: Cannot access 'PullToRefresh' before initialization

angular verison 8.2
nativescript 6

**Comment by NazimMertBilgi** [comment]
same problem.

**Comment by iamabs2001** [comment]
> same problem.

I used radlistview to achieve pullToRefresh

**Comment by bradmartin** [comment]
I believe that is likely a timing issue with angular. I would try wrapping the access inside a `timeout` or using `NgZone` with `this._zone.run(() => { // access it now });` and one of those should work in the angular context
