### ISSUE TITLE
NativeScript 7 Support

### ISSUE THREAD

**Issue by hrueger** [nstudio/nativescript-pulltorefresh#76]
Could you please add support for NativeScript 7?

https://nativescript.org/blog/nativescript-7-for-plugin-authors/
https://nativescript.org/blog/nativescript-7-compatible-plugins/

**Comment by dammynex** [comment]
Any update on this?

**Comment by bradmartin** [comment]
@nstudio/nativescript-pulltorefresh: "~3.0.0"

was published and should work with NS7.

This blog post is trying to maintain a list of plugins that we know of that support NS7 - https://nativescript.org/blog/nativescript-7-compatible-plugins/
